# Inspired from https://github.com/BurntSushi/ripgrep/blob/master/appveyor.yml
cache:
  - c:\cargo\registry
  - c:\cargo\git
  - c:\projects\scavenger\target

init:
  - mkdir c:\cargo
  - mkdir c:\rustup
  - SET PATH=c:\cargo\bin;%PATH%

clone_folder: c:\projects\scavenger

environment:
  CARGO_HOME: "c:\\cargo"
  RUSTUP_HOME: "c:\\rustup"
  CARGO_TARGET_DIR: "c:\\projects\\scavenger\\target"
  global:
    PROJECT_NAME: scavenger
    RUST_BACKTRACE: full
  matrix:
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable

matrix:
  fast_finish: true

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --no-modify-path
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V

# ???
build: false

# Equivalent to Travis' `script` phase
# TODO modify this phase as you see fit
test_script:
  - cargo test --verbose --all

# before_deploy:
#   # Generate artifacts for release
#   - cargo build --release
#   - mkdir staging
#   - copy target\release\rg.exe staging
#   - ps: copy target\release\build\scavenger-*\out\_rg.ps1 staging
#   - cd staging
#     # release zipfile will look like 'rust-everywhere-v1.2.3-x86_64-pc-windows-msvc'
#   - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
#   - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

# deploy:
#   description: 'Automatically deployed release'
#   # All the zipped artifacts will be deployed
#   artifact: /.*\.zip/
#   auth_token:
#     secure: vv4vBCEosGlyQjaEC1+kraP2P6O4CQSa+Tw50oHWFTGcmuXxaWS0/yEXbxsIRLpw
#   provider: GitHub
#   # deploy when a new tag is pushed and only on the stable channel
#   on:
#     # channel to use to produce the release artifacts
#     # NOTE make sure you only release *once* per target
#     # TODO you may want to pick a different channel
#     CHANNEL: stable
#     appveyor_repo_tag: true

branches:
  only:
    - /\d+\.\d+\.\d+/
    - master
    # - appveyor
    # - /\d+\.\d+\.\d+/
  # except:
    # - master
